server:
  port: ${APPLICATION_PORT:8084}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:54326/postgres?currentSchema=notification_service_schema}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog-master.yaml

kafka:
  consumer:
    delivery-status-event:
      topic: ${DELIVERY_STATUS_EVENT_TOPIC:delivery-status-event-local}
      consumer-group-id: ${DELIVERY_STATUS_EVENT_CONSUMER_GROUP:notification-service-delivery-status-event-group-local}
      cluster:
        bootstrap-servers: ${DELIVERY_STATUS_EVENT_BOOTSTRAP_SERVERS:localhost:9092}

feign:
  client:
    config:
      market-service:
        url: ${MARKET_SERVICE_URL:http://localhost:8082}

logging:
  level:
    com.bmo.common.notification_service: ${APPLICATION_DEBUG_LEVEL:DEBUG}